name: PR Checks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  main:
    name: Check types, lint and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "npm"

      - run: npm ci

      - name: Check types
        run: npm run check-types

      - name: Linting
        run: npm run lint

      - name: Testing
        run: xvfb-run -a npm test

      - name: Package VSIX
        run: npx @vscode/vsce package --no-dependencies --out agent-frame.vsix
